export const lodgingSchema = {
  '@context': 'https://schema.org',
  '@type': ['LodgingBusiness', 'Hostel'],
  name: 'Hostal Nómada',
  description:
    'Hostal boutique en edificio Art Déco de 1948 en el centro histórico de Santiago de los Caballeros, República Dominicana. Habitaciones privadas y compartidas. Cervecería Búcaro en el mismo espacio.',
  url: 'https://hostalnomadard.com',
  telephone: '+18297557202',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'C/ Benito Monción 29, esq. Máximo Gómez 34',
    addressLocality: 'Santiago de los Caballeros',
    addressRegion: 'Santiago',
    postalCode: '51000',
    addressCountry: 'DO',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: '19.4521542',
    longitude: '-70.7066258',
  },
  hasMap: 'https://maps.google.com/?q=Hostal+Nómada+Santiago+de+los+Caballeros',
  image: [
    'https://hostalnomadard.com/images/fachada.jpg',
    'https://hostalnomadard.com/images/entrada.jpg',
  ],
  checkinTime: 'T15:00',
  checkoutTime: 'T11:00',
  petsAllowed: true,
  priceRange: 'DOP 900–2400',
  currenciesAccepted: 'DOP, USD',
  numberOfRooms: 4,
  amenityFeature: [
    { '@type': 'LocationFeatureSpecification', name: 'WiFi', value: true },
    { '@type': 'LocationFeatureSpecification', name: 'Air conditioning', value: true },
    { '@type': 'LocationFeatureSpecification', name: 'Free parking', value: true },
    { '@type': 'LocationFeatureSpecification', name: 'Hot shower', value: true },
    { '@type': 'LocationFeatureSpecification', name: 'Smart lock', value: true },
    { '@type': 'LocationFeatureSpecification', name: 'Pets allowed', value: true },
    { '@type': 'LocationFeatureSpecification', name: 'On-site brewery', value: true },
  ],
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.64',
    reviewCount: '457',
    bestRating: '5',
    worstRating: '1',
  },
  sameAs: [
    'https://www.airbnb.com/rooms/hostalnomada',
    'https://www.hostelworld.com/hosteldetails.php/Hostal-Nomada',
  ],
}
